### ISSUE TITLE
Why this tool execute one command constantly for many times?

### ISSUE THREAD

**Issue by TTWen** [TaxyAI/browser-extension#10]
I typed"star the current repository"
it executed many times, star、unstar、star、unstar.... 
![1680074464735](https://user-images.githubusercontent.com/27891446/228456887-c8c48ade-1372-44e3-84f2-d326f1ab33ad.jpg)

**Comment by corbt** [comment]
Yes, unfortunately this is something we've seen with the GPT-3.5 backend. If you have access to GPT-4 it does far better on this. That said, we can also detect this client-side and fail if we're literally repeating the same command multiple times without producing a new result.

**Comment by TTWen** [comment]
> Yes, unfortunately this is something we've seen with the GPT-3.5 backend. If you have access to GPT-4 it does far better on this. That said, we can also detect this client-side and fail if we're literally repeating the same command multiple times without producing a new result.

Thanks, will try 4.0
