### ISSUE TITLE
Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by JacobFV** [TaxyAI/browser-extension#11]
I followed the steps in the readme to setup this extension. However, when I click the green "start task" button, a red rounded rectangle appears at the bottom of the TaxiAI extension box. It says "Could not establish connection. Receiving end does not exist." I did not observe any network traffic in the "network" chrome extension panel, and I did not observe any error or logging message in the console.

**Comment by JacobFV** [comment]
This message appears in the chrome://extension details view:

![Screenshot from 2023-03-29 12-44-04](https://user-images.githubusercontent.com/40343913/228623657-52c4b853-9316-4b43-8ae7-379b793be82a.png)

**Comment by corbt** [comment]
Yes, this is a bug I've run into as well while developing. We run code in both the extension and a content script in the browser context. This error means that the extension code is not able to communicate with the content script (which it has to do to read the page's DOM).

When this happens, often just refreshing the current page and then opening/closing the extension window solves it. If not, you can try reloading the extension and doing the same thing.

Before wider release we definitely want to do a better job of at a minimum messaging what's going wrong and letting the user know how to solve it.

**Comment by JacobFV** [comment]
(reply sent using TaxiAI) :)
