### ISSUE TITLE
Failed to attach debugger: Cannot access a chrome-extension:// URL of different extension

### ISSUE THREAD

**Issue by abbaskhank** [TaxyAI/browser-extension#14]
Getting this error after clicking on start task for any website

**Comment by abbaskhank** [comment]
Context
devtools://devtools/bundled/devtools_app.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@772095164c7d5d4e73160f858efed3b5e87eca83/&can_dock=true&panel=elements
Stack Trace
panel.bundle.js:123435 (_callee$)
panel.bundle.js:123416 (tryCatch)
panel.bundle.js:123416 (anonymous function)
panel.bundle.js:123416 (anonymous function)
panel.bundle.js:123417 (asyncGeneratorStep)
panel.bundle.js:123418 (_next)
panel.bundle.js:123418 (anonymous function)
panel.bundle.js:123418 (anonymous function)

**Comment by arcticfly** [comment]
Thanks for posting this @abbaskhank. What url were you navigated to when you got this error?

**Comment by abbaskhank** [comment]
https://www.sec.gov/
I didn't work on any of the url i tried.

**Comment by arcticfly** [comment]
Also, what other chrome extensions do you have installed? We've found that some (I'm looking at you DashLane and LastPass) interfere with the extension's interactions and cause an error like the one you saw. We disable those particular extensions programmatically while executing, then reenable them after the workflow is complete.

**Comment by arcticfly** [comment]
> https://www.sec.gov/ I didn't work on any of the url i tried.

Could you give an example prompt for me to debug?

**Comment by abbaskhank** [comment]
I disabled all extensions, it still didn't work.

**Comment by abbaskhank** [comment]
Ohh wait, I removed Taxy plug-in, retried and it works now. Thank you!

I will play around and let you know if I find any other issues.

**Comment by arcticfly** [comment]
Awesome! Would you mind sharing any chrome extensions that you had enabled at the time that could have modified the page? I can add them to our "temporarily disable" list.

**Comment by abbaskhank** [comment]
![Screen Shot 2023-03-30 at 3 24 05 PM](https://user-images.githubusercontent.com/11037001/228942494-4dd059a6-14d7-4caa-8272-80a2d9928ddf.png)

**Comment by arcticfly** [comment]
> Do you see it working in a headless browser? I'm working on use case where a headless browser would be a great fit.

Yeah! In fact, that's something we've experimented with a little in the https://github.com/taxyai/experiments repo, and is definitely on our roadmap. Would you mind filling out the [waitlist](https://docs.google.com/forms/u/3/d/e/1FAIpQLScAFKI1fZ1cXhBmSp2HM93Jvuc8Jvrxh5iSbkKhtwKN-OHoTQ/viewform) with your use cases? That's how we're currently keeping track of them.

**Comment by abbaskhank** [comment]
will do, thank you!

**Comment by slavakurilyak** [comment]
I'm seeing the same issue on multiple URLs
