### ISSUE TITLE
fork and launch? permission request

### ISSUE THREAD

**Issue by seshubonam** [TaxyAI/browser-extension#36]
can i fork this repo for a commercial launch allowing access from my website. 
really like the implementation compared to other alternatives like gpt-assistant or puppeteer implementations. 
asking for permission here. will close the issue soon too. 
let me know your thoughts, could help others build, experiment with users and add features to open source. 
Planning to open source my additions too.

**Comment by arcticfly** [comment]
We don't have any problem with that! We aren't actively building a company around this browser extension at the moment. If you could submit PR's with useful changes back to this repo, we'd appreciate it!
